global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "metric_simulators"
    scrape_interval: 10s # 可以为这个 job 设置特定的抓取间隔
    static_configs:
      - targets: ["metric_sim_1:8080", "metric_sim_2:8080"]
        labels:
          service: "metric-simulator"
          # instance 标签将由 Prometheus 根据 target 自动生成，例如 metric_sim_1:8080